### ISSUE TITLE
Homebridge, crypto error.

### ISSUE THREAD

**Issue by TLCary** [patrikx3/openwrt-insomnia#2]
Open to suggestions..  Appreciate the work you've done. No way I ever make it work without you.
Suggestions?  I see:
`crw-------    1 root     root       10,  58 Mar  6 19:08 /dev/crypto
`
````
Fri Mar  6 20:09:40 2020 daemon.err homebridge[4766]: Could not open /dev/crypto: Permission denied
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]: internal/modules/cjs/loader.js:796
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     throw err;
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     ^
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]: Error: Cannot find module 'hap-nodejs/lib/util/once'
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]: Require stack:
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]: - /usr/lib/node/homebridge/lib/server.js
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]: - /usr/lib/node/homebridge/lib/cli.js
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]: - /usr/lib/node/homebridge/bin/homebridge
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Module.require (internal/modules/cjs/loader.js:848:19)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at require (internal/modules/cjs/helpers.js:74:18)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Object.<anonymous> (/usr/lib/node/homebridge/lib/server.js:10:12)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Module._compile (internal/modules/cjs/loader.js:955:30)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Module.load (internal/modules/cjs/loader.js:811:32)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     at Module.require (internal/modules/cjs/loader.js:848:19) {
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:   code: 'MODULE_NOT_FOUND',
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:   requireStack: [
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     '/usr/lib/node/homebridge/lib/server.js',
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     '/usr/lib/node/homebridge/lib/cli.js',
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:     '/usr/lib/node/homebridge/bin/homebridge'
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]:   ]
Fri Mar  6 20:09:41 2020 daemon.err homebridge[4766]: }
```

**Comment by TLCary** [comment]
I have Homebridge working on OpenWRT thanks to your help. Thank You! Installing the Openwrt Firmware and adding Homebridge (and its newer nodejs) from Insomnia worked. I had to manually install the avahi dependancie.  To get that to install without errors I had to add a "netdev" group. Good to have it going. Appreciate the work you do.  I will flash it back and test the crypto from Insomnia on my WRT3200ACM. That would be a nice add. I'll post back and let you know how it goes.
